version: 2.1

defaults: &defaults
  resource_class: small
  working_directory: ~/vervet
  docker:
    - image: circleci/golang:1.16-node

jobs:
  test:
    <<: *defaults
    steps:
      - run:
          name: Install spectral
          command: sudo npm install -g @stoplight/spectral@6.0.0-alpha3
      - checkout
      - attach_workspace:
          at: ~/vervet
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - '/go/pkg/mod'
      - run:
          name: Verify testdata/output up to date
          command: go generate ./testdata
      - run:
          name: Run tests
          command: go test ./... -count=1
      - run:
          command: make -C vervet-underground test

  lint:
    docker:
      - image: golangci/golangci-lint:v1.42.1
    steps:
      - checkout
      - attach_workspace:
          at: ~/vervet
      - run:
          command: golangci-lint run -v ./...

  lint-vu:
    docker:
      - image: golangci/golangci-lint:v1.42.1
    steps:
      - checkout
      - attach_workspace:
          at: ~/vervet/vervet-underground
      - run:
          command: golangci-lint run -v ./...

  release:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build package
          command: ./scripts/dist.bash
      - run:
          name: Release package
          command: cd dist; npx semantic-release -b main

workflows:
  version: 2
  test:
    jobs:
      - test:
          name: Test
  release:
    jobs:
      - test:
          name: Test
          filters:
            branches:
              only: 'main'
      - release:
          name: Release
          context: nodejs-app-release
          requires:
            - Test
          filters:
            branches:
              only: 'main'
  lint:
    jobs:
      - lint:
          name: Lint
      - lint-vu:
          name: Lint VU
