version: 2.1

defaults: &defaults
  resource_class: small
  working_directory: ~/vervet

jobs:
  test:
    <<: *defaults
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - attach_workspace:
          at: ~/vervet
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Verify testdata/output up to date
          command: go generate ./testdata
      - run:
          name: Run tests
          command: go test ./... -count=1

workflows:
  version: 2
  test:
    jobs:
      - test:
          name: Test
